services:
  card-service:
    container_name: card-service
    image: card-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    restart:
      always
    depends_on:
      - card-db
    networks:
      - app-network

  card-db:
    image: postgres:latest
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: card-db
    restart: always
    networks:
      - app-network
    container_name: card-db

networks:
  app-network:
    external: true
